server.port=8080

app.mode=live
app.reg-no=RA2311003011887
app.base-url=https://devapigw.vidalhealthtpa.com/srm-quiz-task
app.poll-count=10
app.delay-millis=5000
app.fixture-path=classpath:data/sample-polls.json
app.live-submit-enabled=true